import json
import os

def create_standalone_html(directory):
    html_path = os.path.join(directory, "index.html")
    json_path = os.path.join(directory, "assets_data.json")
    
    with open(json_path, 'r') as f:
        assets_json = f.read()
    
    with open(html_path, 'r', encoding='utf-8') as f:
        html_content = f.read()
    
    # Replace the empty ASSETS_DATA object with the actual JSON content
    old_string = "const ASSETS_DATA = {}; // Will be filled by script or manually"
    new_string = f"const ASSETS_DATA = {assets_json};"
    
    html_content = html_content.replace(old_string, new_string)
    
    # Also update the init function to use the constant instead of fetching
    old_init = """async function init() {
    // Load asset data from the JSON generated by Python
    const response = await fetch('assets_data.json');
    const assetMap = await response.json();"""
    
    new_init = """async function init() {
    const assetMap = ASSETS_DATA;"""
    
    html_content = html_content.replace(old_init, new_init)
    
    standalone_path = os.path.join(directory, "puzzle_web.html")
    with open(standalone_path, 'w', encoding='utf-8') as f:
        f.write(html_content)
    
    print(f"Standalone HTML created: {standalone_path}")

if __name__ == "__main__":
    create_standalone_html(r"C:\Users\藤本　羽奏\puzzle")
